services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d students_db"]
      interval: 10s
      timeout: 4s
      retries: 3

  api:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: